create table if not exists public.spotify_snapshots (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null,
  source_url text not null,
  hash text not null,
  changed boolean not null default false,
  previous_hash text,
  artists jsonb not null default '[]'::jsonb,
  profile_stats jsonb not null default '{}'::jsonb,
  profile_stats_changed boolean not null default false,
  follower_lists jsonb not null default '{}'::jsonb,
  follower_lists_changed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.spotify_events (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null,
  type text not null,
  top_artist jsonb,
  artists jsonb not null default '[]'::jsonb,
  added jsonb not null default '[]'::jsonb,
  removed jsonb not null default '[]'::jsonb,
  profile_stats jsonb,
  previous_profile_stats jsonb,
  count_changes jsonb not null default '[]'::jsonb,
  follower_list_kind text,
  added_users jsonb not null default '[]'::jsonb,
  removed_users jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.spotify_tracker_state (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.spotify_snapshots
  add column if not exists profile_stats jsonb not null default '{}'::jsonb,
  add column if not exists profile_stats_changed boolean not null default false,
  add column if not exists follower_lists jsonb not null default '{}'::jsonb,
  add column if not exists follower_lists_changed boolean not null default false;

alter table public.spotify_events
  add column if not exists profile_stats jsonb,
  add column if not exists previous_profile_stats jsonb,
  add column if not exists count_changes jsonb not null default '[]'::jsonb,
  add column if not exists follower_list_kind text,
  add column if not exists added_users jsonb not null default '[]'::jsonb,
  add column if not exists removed_users jsonb not null default '[]'::jsonb;

create index if not exists spotify_snapshots_observed_at_idx
  on public.spotify_snapshots (observed_at desc);

create index if not exists spotify_events_observed_at_idx
  on public.spotify_events (observed_at desc);

alter table public.spotify_snapshots enable row level security;
alter table public.spotify_events enable row level security;
alter table public.spotify_tracker_state enable row level security;

drop policy if exists "Public read snapshots" on public.spotify_snapshots;
create policy "Public read snapshots"
  on public.spotify_snapshots for select
  using (true);

drop policy if exists "Public read events" on public.spotify_events;
create policy "Public read events"
  on public.spotify_events for select
  using (true);

drop policy if exists "Public read tracker state" on public.spotify_tracker_state;
create policy "Public read tracker state"
  on public.spotify_tracker_state for select
  using (true);
